# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YourMusicMap' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YourMusicMap
    
   pod 'GoogleMaps'
   pod 'GooglePlaces'
   pod 'SwiftyJSON', '~> 4.0'
   pod 'MBProgressHUD', '~> 0.8'
   pod 'SDWebImage', '~>3.6'

end
